title: "Pradnyanand Bhadarge"
description: "AI & ML Enthusiast | Portfolio"
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

title: "Pradnyanand Bhadarge"
description: "AI & ML Enthusiast | Portfolio"

author:
  name: "Pradnyanand"
  email: "Pradnyanand09@gmail.com"
  linkedin: "https://www.linkedin.com/in/pradnyanand-bhadarge-741979257/"
  github: "https://github.com/Pradnyanand09"

# Navbar menu
nav:
  - title: "About"
    url: /#about
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /#resume
  - title: "Contact"
    url: /#contact

